server:
  port: 7001
notice:
  wxwork:
    project-code: wxwork-bot-key
logging:
  file:
    name: tushansusu.log
  level:
    com.github.tomseanmy.tushansusu: info

spring:
  main:
    banner-mode: off
