name: tushansusu ci

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          components: 'native-image'
          cache: maven
      - name: Build with Maven
        run: mvn -Pnative package native:compile-no-fork -f pom.xml
      - name: Release Github
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: test action
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Upload Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/tushansusu
          asset_name: tushansusu-${{ steps.get_version.outputs.VERSION }}
          asset_content_type: application/octet-stream