name: tushansusu ci

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          cache: maven
      - name: Build with Maven
        run: mvn -Pnative package
      - name: Get commit messages
        id: get_commits
        run: |
          COMMITS=$(git log --pretty=format:"%s" ${{ github.sha }}^..HEAD)
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
      - name: Release Github
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ${{ steps.get_commits.outputs.COMMITS }}
      - name: Upload Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/tushansusu
          asset_name: tushansusu-v${{ github.ref }}
          asset_content_type: application/octet-stream